-- AlterTable
ALTER TABLE "configuraciones_pedido" ADD COLUMN     "anticipo" DOUBLE PRECISION,
ADD COLUMN     "costoAduana" DOUBLE PRECISION,
ADD COLUMN     "costoFlete" DOUBLE PRECISION,
ADD COLUMN     "costoOtros" DOUBLE PRECISION,
ADD COLUMN     "costoProveedor" DOUBLE PRECISION,
ADD COLUMN     "costoTotal" DOUBLE PRECISION,
ADD COLUMN     "estadoPedido" TEXT NOT NULL DEFAULT 'consulta',
ADD COLUMN     "fechaArriboEstimado" TIMESTAMP(3),
ADD COLUMN     "fechaConfirmacion" TIMESTAMP(3),
ADD COLUMN     "fechaDespacho" TIMESTAMP(3),
ADD COLUMN     "fechaEntrega" TIMESTAMP(3),
ADD COLUMN     "fechaProduccion" TIMESTAMP(3),
ADD COLUMN     "margenPorcentaje" DOUBLE PRECISION,
ADD COLUMN     "margenUSD" DOUBLE PRECISION,
ADD COLUMN     "notasCliente" TEXT,
ADD COLUMN     "notasInternas" TEXT,
ADD COLUMN     "numeroBL" TEXT,
ADD COLUMN     "numeroContenedor" TEXT,
ADD COLUMN     "numeroFabrica" TEXT,
ADD COLUMN     "numeroPedido" TEXT,
ADD COLUMN     "precioFinal" DOUBLE PRECISION,
ADD COLUMN     "saldoPendiente" DOUBLE PRECISION;
